config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'books#index'

  resources :books
  resources :download_links
  resources :comments, only: [:create, :destroy, :update]

  namespace :admin do
    resources :books, only: [:index, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  def comments_form
    "#{message} <br /> <span class='edit_link'> Редактировать </span>".html_safe
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Comment.all.page(params[:page])
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to admin_comments_path, notice: 'Комментарий успешно отредактирован.'
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    authorize Comment
    @comment = Comment.new(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @comment.save
        format.js { render json: { html: render_to_string(partial: 'comments/comment', locals: { comment: @comment }) } }
      else
        format.js { render json: { errors: @comment.errors.full_messages.join(' ') } }
      end
    end
  end

  def update
    @comment = Comment.find params[:id]

    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.json { respond_with_bip(@comment) }
      else
        format.json { respond_with_bip(@comment) }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:book_id, :user_id, :message)
  end
end

app/views/admin/comments/edit.html.slim
h4 Редактирование комментария:
= simple_form_for @comment, url: admin_comment_path(@comment) do |f|
  = f.input :message, input_html: { class: "materialize-textarea validate", length: "750" }, required: true
  .input-field.col.s9
    = f.submit 'Сохранить', class: 'waves-effect waves-light btn indigo lighten-2'
    = link_to 'Назад', :back, class: 'btn indigo lighten-5'

app/views/admin/comments/index.html.slim
h3.title Комментарии

table.striped
  thead
    tr
      th Пользователь
      th Комментарий
      th Книга
      th Действия
  tbody
    - @comments.each do |comment|
      tr
        td = comment.user.username
        td = comment.message
        td = comment.book.title
        td
          = link_to edit_admin_comment_path(comment), class: 'action_link admin-links' do
            i class='material-icons' mode_edit
          = link_to admin_comment_path(comment), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'action_link admin-links' do
            i class='material-icons' delete

= paginate @comments