config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'books#index'

  resources :books
  resources :download_links
  resources :comments, only: [:create, :destroy, :update]

  namespace :admin do
    resources :books, only: [:index, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :books
  has_many :comments

  after_create :assign_role

  enum role: [:member, :local, :librarian, :admin]

  def has_role?(role)
    self.role == role
  end

  def owner?(resource)
    resource.user_id == self.id
  end

  def admin?
    role == 'admin'
  end

  private

  def assign_role
    self.member!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(params.require(:user).permit(:role))
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/edit.html.slim
h4 Редактирование пользователя:
= simple_form_for [:admin, @user] do |f|
  = f.input :username, readonly: true
  = f.input :email, readonly: true
  = f.input :role, collection: User.roles
  .input-field.col.s9
    = f.submit 'Сохранить', class: 'waves-effect waves-light btn indigo lighten-2'
    = link_to 'Назад', :back, class: 'btn indigo lighten-5'

app/views/admin/users/index.html.slim
h3.title Пользователи

table.striped
  thead
    tr
      th Имя
      th Email
      th Роль
      th Действия
  tbody
    - @users.each do |user|
      tr
        td = user.username
        td = user.email
        td = user.role
        td
          = link_to edit_admin_user_path(user), class: 'action_link admin-links' do
            i class='material-icons' mode_edit
          - unless current_user == user
            = link_to admin_user_path(user), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'action_link admin-links' do
              i class='material-icons' delete

= paginate @users