config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'books#index'

  resources :books
  resources :download_links
  resources :comments, only: [:create, :destroy, :update]

  namespace :admin do
    resources :books, only: [:index, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end
end

app/views/layouts/_navbar.html.slim
/nav
/  .nav-wrapper.indigo.lighten-3
/    = link_to 'Library', root_path, class: 'brand-logo'
/    ul#nav-mobile.right.hide-on-med-and-down
/      - if user_signed_in?
/
/        /- if policy(Book).new?
/        /  li = link_to 'Добавить книгу', new_book_path
/        li Вы зашли под именем #{current_user.username}
/        li = link_to('Выйти', destroy_user_session_path, method: :delete)
/      - else
/        li = link_to('Войти', new_user_session_path)
/        li = link_to('Зарегистрироваться', new_user_registration_path)

/! Dropdown Structure
ul#admin-dropdown.dropdown-content
  li = link_to 'Добавить книгу', new_book_path
  li = link_to 'Книги', admin_books_path
  li = link_to 'Комментарии', admin_comments_path
  li = link_to 'Пользователи', admin_users_path
nav
  .nav-wrapper.indigo.lighten-3
    = link_to 'Library', root_path, class: 'brand-logo'
    ul.right.hide-on-med-and-down
      - if user_signed_in?
        li Вы зашли под именем #{current_user.username}
        li = link_to('Выйти', destroy_user_session_path, method: :delete)
        - if current_user.admin?
          li
            a.dropdown-button data-activates="admin-dropdown" href="#!"
              | Управление
              i.material-icons.right arrow_drop_down

app/views/layouts/_sidebar.html.slim
/ul.collapsible data-collapsible="expandable"
/  - Category.roots.each do |root|
/    li.collection-item
/      .collapsible-header.categories = root.name
/      .collapsible-body
/        p.subcategories
/          - root.children.each do |child|
/            span
/              = link_to child.name, root_path(category: child.name)
/              br
/
//javascript:
//  $('.collapsible').collapsible({
//    expandable: true
//  });

ul.collection.categories
  - Category.all.each do |category|
    li.collection-item = link_to category.name, root_path(category: category.name)

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Library Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      .row.main-row
        - flash.each do |name, msg|
          = content_tag :div, msg, class: name
        .col.s1
        .col.s11.main-block
          = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Library
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      .row.main-row
        - flash.each do |name, msg|
          = content_tag :div, msg, class: name
        .col.s3
          = render 'layouts/sidebar'
        .col.s9.main-block
          = yield